using System.Collections.Generic;
using System.IO;
using System.IO.Abstractions;
using FellowOakDicom;
using IsIdentifiable.Failures;

namespace IsIdentifiable.Reporting;

/// <summary>
/// Generates <see cref="Failure"/> objects based on the content of <see cref="DicomFile"/>.
/// The <see cref="Failure.ResourcePrimaryKey"/> of failures generated by this class is
/// SOPInstanceUID.
/// </summary>
class DicomFileFailureFactory
{
    public Failure Create(IFileInfo file, DicomFile dcm, string problemValue, string problemField, IEnumerable<FailurePart> parts)
    {
        string resourcePrimaryKey;
        try
        {
            // Some DICOM files do not have SOPInstanceUID
            resourcePrimaryKey = dcm.Dataset.GetSingleValue<string>(DicomTag.SOPInstanceUID);
        }
        catch (DicomDataException)
        {
            resourcePrimaryKey = "UnknownPrimaryKey";
        }
        return new Failure(parts)
        {
            Resource = file.FullName,
            ResourcePrimaryKey = resourcePrimaryKey,
            ProblemValue = problemValue,
            ProblemField = problemField
        };
    }
}